import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
export const colors={bg:'#F5F7FB',surface:'#FFFFFF',ink:'#172033',muted:'#64748B',brand:'#3157D5',soft:'#E9EEFF',green:'#13805A',red:'#BE4242',line:'#E2E8F0'};
export function Page({children}:{children:React.ReactNode}){const insets=useSafeAreaInsets();return <View style={[styles.page,{paddingBottom:Math.max(insets.bottom,16)+24}]}>{children}</View>}
export function Title({children,sub}:{children:React.ReactNode;sub?:string}){return <View style={{marginBottom:20}}><Text style={styles.title}>{children}</Text>{sub?<Text style={styles.sub}>{sub}</Text>:null}</View>}
export function Card({children,onPress}:{children:React.ReactNode;onPress?:()=>void}){const body=<View style={styles.card}>{children}</View>;return onPress?<Pressable onPress={onPress} accessibilityRole="button">{body}</Pressable>:body}
export function Button({title,onPress,disabled=false}:{title:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.button,disabled&&{opacity:.45}]}><Text style={styles.buttonText}>{title}</Text></Pressable>}
export const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.bg,paddingHorizontal:22,paddingTop:18},title:{fontSize:28,fontWeight:'800',color:colors.ink},sub:{fontSize:15,color:colors.muted,marginTop:7,lineHeight:22},card:{backgroundColor:colors.surface,borderRadius:18,padding:18,marginBottom:12,borderWidth:1,borderColor:colors.line},button:{backgroundColor:colors.brand,padding:16,borderRadius:14,alignItems:'center',marginTop:12},buttonText:{color:'white',fontWeight:'700',fontSize:16},label:{fontSize:12,textTransform:'uppercase',letterSpacing:1,color:colors.muted,fontWeight:'700'}});
